"""empty message

Revision ID: 20f021ea43c1
Revises: 
Create Date: 2025-07-17 09:31:30.669994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20f021ea43c1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paciente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dni', sa.String(length=20), nullable=True))
        batch_op.create_unique_constraint('uq_paciente_dni', ['dni'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paciente', schema=None) as batch_op:
        batch_op.drop_constraint('uq_paciente_dni', type_='unique')
        batch_op.drop_column('dni')

    # ### end Alembic commands ###
