"""add indicaciones to consulta model

Revision ID: 361297cd3305
Revises: e9a8955aff1a
Create Date: 2025-08-09 22:38:46.901286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '361297cd3305'
down_revision = 'e9a8955aff1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consulta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('indicaciones', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consulta', schema=None) as batch_op:
        batch_op.drop_column('indicaciones')

    # ### end Alembic commands ###
