"""Add fecha_nacimiento to Paciente model

Revision ID: e9a8955aff1a
Revises: 20f021ea43c1
Create Date: 2025-07-17 18:29:52.477864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9a8955aff1a'
down_revision = '20f021ea43c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paciente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_nacimiento', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paciente', schema=None) as batch_op:
        batch_op.drop_column('fecha_nacimiento')

    # ### end Alembic commands ###
